spring:
    datasource:
      url: jdbc:mysql://localhost:3306/blogapi
      username: root
      password: Rahul@3178
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true

    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
